CREATE TABLE IF NOT EXISTS players (
	player_id INT(25) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	credits INT(9) NOT NULL,
	lifetime_spins INT(12) NOT NULL,
	salt_value VARCHAR(255) NOT NULL
) ENGINE=InnoDB CHARSET=utf8 COLLATE=utf8_unicode_ci;
